# Generated by Django 2.1.5 on 2021-08-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20210729_2343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Movie',
        ),
    ]
