# Generated by Django 2.1.5 on 2021-08-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20210803_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Movie_hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_number', models.IntegerField()),
            ],
            options={
                'db_table': 'Movie_hot',
                'ordering': ['-rating_number'],
            },
        ),
        migrations.CreateModel(
            name='Movie_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release_time',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rango.User'),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='Movie',
        ),
        migrations.AddField(
            model_name='user',
            name='rating_movies',
            field=models.ManyToManyField(through='rango.Movie_rating', to='rango.Movie'),
        ),
        migrations.AddField(
            model_name='movie_rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Movie'),
        ),
        migrations.AddField(
            model_name='movie_rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.User'),
        ),
        migrations.AddField(
            model_name='movie_hot',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='rango.Genre'),
        ),
    ]
